version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - talebi-db-data:/var/lib/postgresql/data
    env_file:
      - ".env"

  backend:
    depends_on:
      - db
    image: hamedhf/talebi-service:lastest
    ports:
      - "443:80"
      - "80:80"
    volumes:
      - .:/usr/src/app
    command: sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn talebi.wsgi:application -c ./talebi/gunicorn.conf.py"
    env_file:
      - ".env"

volumes:
  talebi-db-data:
