version: "3.8"

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - talebi-db-data:/var/lib/postgresql/data
    env_file:
      - ".env"

  backend:
    depends_on:
      - db
    image: hamedhf/talebi-service:lastest
    ports:
      - "443:80"
      - "80:80"
    command: sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn --bind=0.0.0.0:80 --worker-tmp-dir=/dev/shm --chdir=/usr/src/app --log-level='info' --log-file=- --workers=2 --threads=4 --worker-class=gthread talebi.wsgi:application"
    env_file:
      - ".env"

volumes:
  talebi-db-data:
