name: service CI

on:
  push:
    branches: [ main ]

jobs:
  build-service:
    name: build service image
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set ip docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/talebi-service:lastest

  deploy-service:
    name: deploy service
    runs-on: ubuntu-latest
    needs: build-service
    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: deploy
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && docker compose down && git checkout ${{ secrets.MAIN_BRANCH }} && git pull && docker compose up -d --build -f server-deploy.yml && exit"

      - name: cleanup
        run: rm -rf ~/.ssh
