name: service CI

on:
  push:
    branches: [ main ]

jobs:
  build-service:
    name: build service image
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set ip docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/talebi-service:lastest
