name: drf tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest

    steps:
      - name: check out source repository
        uses: actions/checkout@v3

      - name: set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: pytest tests
        uses: cclauss/GitHub-Action-for-pytest@0.5.0
