name: drf tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest

    services:
      postgres:
        image: postgres:15.2-alpine
        env:
          POSTGRES_USER: talebi
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: talebi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7.2-rc2-alpine
        ports:
          - 6379:6379

    steps:
      - name: check out source repository
        uses: actions/checkout@v3

      - name: set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install dependencies
        env:
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root --no-interaction --no-ansi

      - name: run pytest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_USER: talebi
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: talebi
          REDIS_HOST: redis
        run: |
          run pytest
